"""
GENERATED by `py -m sentinel_lanes sync` from sentinel-watchdog/shared/lanes.yaml
DO NOT EDIT — your changes will be overwritten. Edit the SoT and re-run sync.

Lane ids name the SLOT, not the weights loaded in it — `sentinel/brain` stays
correct across a 27B, a MoE 30B or a 12B. Never put a model version or a
parameter count in one of these.
"""

# lane -> canonical wire id
BRAIN = "sentinel/brain"  # :1234 (live)
REFLEX = "sentinel/reflex"  # :1237 (dormant)
LAB = "sentinel/lab"  # :1235 (reserved)

# Every id a lane still answers to, canonical first. Legacy aliases are
# transitional — read from here rather than hardcoding an old string.
LANE_IDS = {
    "brain": ("sentinel/brain", "qwen/qwen3.6-27b",),
    "reflex": ("sentinel/reflex", "qwen3-4b",),
    "lab": ("sentinel/lab",),
}

# lane -> base url of the local server that answers for it
LANE_BASE_URLS = {
    "brain": "http://127.0.0.1:1234",
    "reflex": "http://127.0.0.1:1237",
    "lab": "http://127.0.0.1:1235",
}
